language: python
python:
  - "3.7"
env:
  - DJANGO="Django>=3.1,<4.0" DB=sqlite
  # Enable Later
  # - DJANGO="Django>=3.1,<4.0" DB=postgres
  # - DJANGO="Django>=3.1,<4.0" DB=mysql

install:
  - if [[ $DB == mysql ]]; then pip install -qU mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -qU psycopg2; fi
  - pip install -qU $DJANGO
  - if [[ $DB == postgres && $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGO_LTS == true ]] ; then export WITH_COVERALL=true ; fi
  - if [[ $WITH_COVERALL == true ]]; then pip install -qU coveralls ; fi
  - CFLAGS="-O0" pip install -qU -r test/test_project/requirements_test.txt
before_script:
  - if [[ $DB == mysql ]]; then mysql -e 'SET GLOBAL wait_timeout = 36000 ; create database pybbm;'; fi
  - if [[ $DB == postgres ]]; then psql -c 'create database pybbm;' -U postgres; fi
script:
  - if [[ $WITH_COVERALL == true ]]; then coverage run setup.py test; else python setup.py test ; fi
after_success:

  - if [[ $WITH_COVERALL == true ]]; then coveralls ; fi
